version: '3.7'

services:

  #
  # Приложение php-fpm с возможностью входа в bash
  # docker-compose exec app bash
  #
  app:
    build:
      args:
        # - USER=sammy
        # - UID=1000
        - DEVELOP=true
      context: ./app
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      # - mongo
      - redis
    volumes:
      - ${APP_CODE}:/var/www/html:delegated
      # - ./xhgui:/var/www/xhgui:delegated   

  #
  # Nginx контейнер, собирается напрямую из образа
  #
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    volumes:
      - ${APP_CODE}:/var/www/html:delegated
      - ./xhgui:/var/www/xhgui:delegated
      - ./log/nginx:/var/log/nginx:delegated
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''  

  #
  # MongoDB
  #
  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/mongo:/data/db:delegated
  #   environment:
  #     MONGO_INITDB_DATABASE: xhprof
  #   command: --storageEngine=wiredTiger

  #
  # Supervisor Worker
  #
  worker:
    build: ./worker
    volumes:
      - ${APP_CODE}:/var/www/html:delegated
      - ./worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - redis

  #
  # Redis
  #
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

networks:
  default:
    external: 
      name: br0  